# Generated by Django 4.2 on 2023-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_menuitem_url_menuitem_slug_alter_menu_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
